name: music_mind_client
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get:
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  firebase_core: ^1.11.0
  http: ^0.13.4
  flutter_dotenv: ^5.0.2
  video_player: ^2.2.15
  chewie: ^1.2.2
  flutter_stripe: ^2.1.1
  sn_progress_dialog: ^1.0.3
  image_picker: ^0.8.4+5
  path: ^1.8.0
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env


  fonts:
    - family: Noto Sans
      fonts:
        - asset: fonts/NotoSans-Bold.ttf
          weight:  700
        - asset: fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans-SemiBold.ttf
          weight: 600
    - family: Red Hat Display
      fonts:
        - asset: fonts/RedHatDisplay-Black.ttf
          weight: 700
        - asset: fonts/RedHatDisplay-Regular.ttf
          weight: 400

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700